version: '3.4'

services:
  vectorquery:
    image: ${DOCKER_REGISTRY}vectorquery
    build:
      context: .
      dockerfile: VectorQuery/Dockerfile
    links:
    - bigbadabom
  bigbadabom:
    container_name: bigbadabom
    image: artsdatabanken/bigbadabom
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
    - D:/Artsdatabanken/Data/bigbadabom:/data
