version: '3.4'

services:
  vectorquery:
    image: vectorquery
    build:
      context: .
      dockerfile: VectorQuery/Dockerfile
    links:
    - vectorquery_bigbadabom
  vectorquery_bigbadabom:
    container_name: vectorquery_bigbadabom
    image: mdillon/postgis
    environment:
      POSTGRES_DB: bigbadabom
    volumes:
    - vectorquery_bigbadabom:/var/lib/postgresql/data

volumes:
    vectorquery_bigbadabom:
        external:
          name: bigbadabom